### ISSUE TITLE
develop ulang

### ISSUE THREAD

**Issue by izzuzantyaf** [izzuzantyaf/fisdasweb#12]
### Todo
- [x] install Next.js
- [x] reinstall Tailwind CSS
- [x] implementasi Typescript
- [x] sesuaikan data fetching dengan [fisdascms-server.herokuapp.com](https://fisdascms-server.herokuapp.com/api)
- [x] implementasi core bussiness entity
- [x] perbaiki penggunaan AppLayout
- [x] perbaiki menu dropdown spacing di navbar
- [x] ganti favicon dan icon
